import { Type } from 'class-transformer';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsDateString,
  IsDefined,
  IsNotEmpty,
  IsObject,
  IsOptional,
  IsString,
  IsUUID,
  ValidateNested,
} from 'class-validator';

import { EventRecipientDto } from './event-recipient.dto';

export class CreateEventDto {
  @ApiPropertyOptional({
    description: 'Stable event identifier. Generated by Producer when omitted.',
    example: '7a6a6e42-4f59-43c8-a8b7-2f43ed1c7a25',
    format: 'uuid',
  })
  @IsOptional()
  @IsUUID()
  eventId?: string;

  @ApiProperty({
    description: 'Domain event type.',
    example: 'order.created',
  })
  @IsString()
  @IsNotEmpty()
  eventType!: string;

  @ApiPropertyOptional({
    description: 'When the event happened. Producer sets current time when omitted.',
    example: '2026-05-02T11:00:00.000Z',
    format: 'date-time',
  })
  @IsOptional()
  @IsDateString()
  occurredAt?: string;

  @ApiProperty({
    description: 'Notification recipient.',
    type: () => EventRecipientDto,
  })
  @IsDefined()
  @ValidateNested()
  @Type(() => EventRecipientDto)
  recipient!: EventRecipientDto;

  @ApiProperty({
    description: 'Arbitrary event payload.',
    type: 'object',
    example: {
      orderId: 'ORD-1001',
      amount: 129.99,
      currency: 'USD',
    },
    additionalProperties: true,
  })
  @IsObject()
  payload!: Record<string, unknown>;

  @ApiPropertyOptional({
    description: 'Correlation identifier used in logs and RabbitMQ headers.',
    example: 'req-01HXEXAMPLE',
  })
  @IsOptional()
  @IsString()
  correlationId?: string;
}
